main: com.haralanov.greentext.GreenText
version: 2.0.0
name: GreenText
author: Beezle
website: github.com/AleksandarHaralanov/GreenText
description: Players can write 4chan-style greentext messages.

permissions:
  greentext.write:
    description: Allows the players to write 4chan-style greentext messages.

commands:
  greentext:
    description: See info about the GreenText plugin.
    usage: /<command>