main: me.beezle.greentext.Greentext
version: 1.0
name: Greentext
authors: [Beezle]
description: Players can make 4chan-like greentext messages.

permissions:
  greentext.use:
    description: Allows the player to make 4chan-like greentext messages.
    default: op